[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m elevenlabs_mcp --server --host 0.0.0.0"
healthcheckPath = "/mcp"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.env]
PYTHONPATH = "/app"

[variables]
HOST = "0.0.0.0"